{% set name = "myjive" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/myjive-{{ version }}.tar.gz
  sha256: df704d3164bc1f900b8ed5093c1aed76af6509e18fe5b148f75c2380be2bc2b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.11
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.10,<3.11
    - matplotlib-base
    - numba
    - numpy
    - pandas
    - scikit-sparse >=0.4.12
    - scipy >=1.12

test:
  imports:
    - myjive
    - myjivex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.tudelft.nl/apoot1/myjive
  summary: Personal implementation of jive C++ library in Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - annepoot
